# Michael Ekstrom 
# CS3505 
CC = g++
CFLAGS = -Wall

powSumation: powSumation.cpp
	g++ -Wall -o $@ $@.cpp

runSum: powSumation
	./powSumation > log.txt


q4: q4.cpp
	g++ -Wall -o $@ $@.cpp

runq4: q4
	./q4 > log2.txt

clean:
	rm -f powSumation
	rm -f log.txt
